theme: jekyll-theme-minimal
logo: face.jpeg
title: Hi there!
description: Also visit me on **[LinkedIn]**(https://www.linkedin.com/in/maike-rees-8b6103150) or **[github]**(https://github.com/maikefer)
