theme: jekyll-theme-minimal
logo: face.png
title: HI, this is me!
description: Hey there, you've found my github.io page! Since it is so simple I thought I should make my own as well. Happy exploring!
